services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tagsdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=tagsdb;Username=postgres;Password=postgres"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:8080"

  frontend:
    build: ./Frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
