name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Pobierz kod repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Zainstaluj .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # 3. Przywróć zależności
      - name: Restore dependencies
        run: dotnet restore

      # 4. Zbuduj projekt
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # 5. Uruchom testy (unit + integration)
      - name: Run tests
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

      # 6. Publikacja wyników testów w GitHub Actions UI
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Tests
          path: TestResults/*.trx
          reporter: dotnet-trx
